default: true
MD013: false # Disable line length limit
MD033: # Allow raw html for specific elements
  allowed_elements:
    - details
    - summary
    - p
    - br
    - script
    - iframe
    - div
