# Site settings
title: Marcos Pereira
email:
author: Marcos Pereira
description: "Marcos Pereira's personal website."
baseurl: ""
url: "https://marcospereira.me"
date_format: "%b %-d, %Y"
header_pages:
  - about-me.md
  - notes.md

# Google analytics
google_tag_manager: G-8NMMK1ZP7T

# Optional features
animated: false
show_social_icons: true
enable_mathjax: true
extended_fonts: true
enable_anchorjs: true
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: marcospgp
twitter_username: voxelbased

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
redcarpet:
  extensions: ["smart", "tables", "with_toc_data"]
permalink: pretty
sass:
  style: compressed
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - _helpers
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
  - README.md
  - PIXYLL.md
  - screenshot.png
  - vendor
# Render posts with future dates. Timezone differences means post with current
# date in author's timezone may not be rendered.
# No current reason to hide future posts either.
future: true

# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 12
  permalink: "/page-:num/"
  # Empty title because pagination is used in homepage, and we don't want to
  # mess with its `<title>`.
  title:
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
