# Site settings
title: Marcos Pereira
email:
author: Marcos Pereira
description: "Marcos Pereira's personal website."
baseurl: ""
url: "https://marcospereira.me"
date_format: "%b %-d, %Y"
header_pages:
  - about-me.md
  - notes.md

# Google analytics
google_tag_manager: G-8NMMK1ZP7T

# Social icons
github_username: marcospgp
twitter_username: voxelbased

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

permalink: pretty

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap

# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - _helpers
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
  - README.md
  - PIXYLL.md
  - screenshot.png
  - vendor

# Render posts with future dates. Timezone differences means posts with current
# date in author's timezone may not be rendered.
# No current reason to hide future posts either.
future: true

# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 999999
  permalink: "/page-:num/"
  # Empty title because pagination is used in homepage, and we don't want to
  # mess with its `<title>`.
  title:
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
