version: "3.9"
services:
  jekyll:
    image: "jekyll/jekyll"
    ports:
      - "4000:4000"
    volumes:
      # The ":Z" comes from docs: https://github.com/envygeeks/jekyll-docker/blob/master/README.md#usage-3
      - ./:/srv/jekyll:Z
    command: jekyll serve --trace
